server:
    port: 8180

spring:
    datasource:
        url: jdbc:h2:mem:db
        driverClassName: org.h2.Driver 
        username: db
        password: db
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect